<a href="https://colab.research.google.com/github/lainaker7/Desafio2-TelecomX/blob/main/TELECOM_X_ALURA_CHALLENGE_Public.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📌 **1. E-xtracción de los Datos**: 📌

In [3]:
# Primer paso es Generar la Extracción de los datos

#📌 Enlace de la API:
#🔗 challenge2-data-science-LATAM/TelecomX_Data.json at main · ingridcristh/challenge2-data-science-LATAM

import pandas as pd

In [4]:
# Si el JSON es directamente un array de objetos
url = "https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json"
df = pd.read_json(url)

# Mostrar las primeras filas
df.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

In [5]:

import requests

# Obtener los datos directamente como diccionario
response = requests.get(url)
data = response.json()

# Normalizar el JSON completo
df_normalized = pd.json_normalize(data)

print("✅ Datos normalizados exitosamente")
print(f"📊 Forma: {df_normalized.shape}")
print("\n🔍 Columnas disponibles:")
for col in df_normalized.columns:
    print(f"  - {col}")

print("\n📋 Primeras 5 filas:")
display(df_normalized.head())

print("\n📊 Información del DataFrame:")
print(df_normalized.info())

✅ Datos normalizados exitosamente
📊 Forma: (7267, 21)

🔍 Columnas disponibles:
  - customerID
  - Churn
  - customer.gender
  - customer.SeniorCitizen
  - customer.Partner
  - customer.Dependents
  - customer.tenure
  - phone.PhoneService
  - phone.MultipleLines
  - internet.InternetService
  - internet.OnlineSecurity
  - internet.OnlineBackup
  - internet.DeviceProtection
  - internet.TechSupport
  - internet.StreamingTV
  - internet.StreamingMovies
  - account.Contract
  - account.PaperlessBilling
  - account.PaymentMethod
  - account.Charges.Monthly
  - account.Charges.Total

📋 Primeras 5 filas:

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

📊 Información del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB
None

## 🔎 *Explorar las columnas del dataset y verificar sus tipos de datos*

In [6]:
print("="*80)
print("✅ PASO 1: EXPLORACIÓN DE COLUMNAS Y TIPOS DE DATOS")
print("="*80)

================================================================================
✅ PASO 1: EXPLORACIÓN DE COLUMNAS Y TIPOS DE DATOS
================================================================================

In [7]:
import numpy as np

# 1.1. Información general del DataFrame
print("\n📊 1.1. INFORMACIÓN GENERAL DEL DATAFRAME:")
print(f"• Número total de filas: {df_normalized.shape[0]:,}")
print(f"• Número total de columnas: {df_normalized.shape[1]}")
print(f"• Memoria usada: {df_normalized.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

# 1.2. Tipos de datos por columna
print("\n📋 1.2. DISTRIBUCIÓN DE TIPOS DE DATOS:")
type_counts = df_normalized.dtypes.value_counts()
for dtype, count in type_counts.items():
    print(f"  {dtype}: {count} columnas ({count/df.shape[1]*100:.1f}%)")

# 1.3. Lista detallada de columnas con sus tipos
print("\n🔍 1.3. LISTA COMPLETA DE COLUMNAS CON SUS TIPOS:")
for i, (col, dtype) in enumerate(df.dtypes.items(), 1):
    print(f"{i:3d}. {col:40} → {dtype}")

# 1.4. Columnas por categoría
print("\n🏷️ 1.4. CLASIFICACIÓN DE COLUMNAS POR CONTENIDO:")

# Identificar columnas categóricas
categorical_cols = df_normalized.select_dtypes(include=['object', 'category']).columns.tolist()
print(f"\n• Columnas categóricas ({len(categorical_cols)}):")
for i, col in enumerate(categorical_cols[:15], 1):
    print(f"  {i:2d}. {col}")
if len(categorical_cols) > 15:
    print(f"  ... y {len(categorical_cols)-15} más")

# Identificar columnas numéricas
numeric_cols = df_normalized.select_dtypes(include=[np.number]).columns.tolist()
print(f"\n• Columnas numéricas ({len(numeric_cols)}):")
for i, col in enumerate(numeric_cols, 1):
    print(f"  {i:2d}. {col}")

# Identificar columnas booleanas (si las hay)
bool_cols = df_normalized.select_dtypes(include=['bool']).columns.tolist()
if bool_cols:
    print(f"\n• Columnas booleanas ({len(bool_cols)}):")
    for i, col in enumerate(bool_cols, 1):
        print(f"  {i:2d}. {col}")

# 1.5. Análisis de valores nulos
print("\n⚠️ 1.5. ANÁLISIS DE VALORES NULOS:")
null_sum = df_normalized.isnull().sum()
null_cols = null_sum[null_sum > 0]
if len(null_cols) > 0:
    print("Columnas con valores nulos:")
    for col, null_count in null_cols.items():
        null_percentage = (null_count / df.shape[0]) * 100
        print(f"  • {col}: {null_count:,} nulos ({null_percentage:.2f}%)")
else:
    print("  ¡No hay valores nulos en el dataset!")

# 1.6. Valores únicos en columnas categóricas importantes
print("\n🎯 1.6. VALORES ÚNICOS EN COLUMNAS CLAVE:")
key_columns = ['Churn', 'customer_gender', 'customer_SeniorCitizen',
               'phone_PhoneService', 'internet_InternetService', 'account_Contract']

for col in key_columns:
    if col in df_normalized.columns:
        unique_vals = df_normalized[col].nunique()
        sample_vals = df_normalized[col].unique()[:5] if unique_vals > 5 else df_normalized[col].unique()
        print(f"\n  {col}:")
        print(f"    • Valores únicos: {unique_vals}")
        print(f"    • Muestra de valores: {sample_vals}")
        print(f"    • Conteo de valores:\n{df_normalized[col].value_counts().head()}")

print("\n" + "="*80)

📊 1.1. INFORMACIÓN GENERAL DEL DATAFRAME:
• Número total de filas: 7,267
• Número total de columnas: 21
• Memoria usada: 7.04 MB

📋 1.2. DISTRIBUCIÓN DE TIPOS DE DATOS:
  object: 18 columnas (300.0%)
  int64: 2 columnas (33.3%)
  float64: 1 columnas (16.7%)

🔍 1.3. LISTA COMPLETA DE COLUMNAS CON SUS TIPOS:
  1. customerID                               → object
  2. Churn                                    → object
  3. customer                                 → object
  4. phone                                    → object
  5. internet                                 → object
  6. account                                  → object

🏷️ 1.4. CLASIFICACIÓN DE COLUMNAS POR CONTENIDO:

• Columnas categóricas (18):
   1. customerID
   2. Churn
   3. customer.gender
   4. customer.Partner
   5. customer.Dependents
   6. phone.PhoneService
   7. phone.MultipleLines
   8. internet.InternetService
   9. internet.OnlineSecurity
  10. internet.OnlineBackup
  11. internet.DeviceProtection
  12. internet.TechSupport
  13. internet.StreamingTV
  14. internet.StreamingMovies
  15. account.Contract
  ... y 3 más

• Columnas numéricas (3):
   1. customer.SeniorCitizen
   2. customer.tenure
   3. account.Charges.Monthly

⚠️ 1.5. ANÁLISIS DE VALORES NULOS:
  ¡No hay valores nulos en el dataset!

🎯 1.6. VALORES ÚNICOS EN COLUMNAS CLAVE:

  Churn:
    • Valores únicos: 3
    • Muestra de valores: ['No' 'Yes' '']
    • Conteo de valores:
Churn
No     5174
Yes    1869
        224
Name: count, dtype: int64

================================================================================

In [8]:
df = df_normalized

In [9]:
# Análisis rápido de calidad de datos
def quick_data_quality_check(df):
    print("🔍 ANÁLISIS RÁPIDO DE CALIDAD DE DATOS")
    print("="*60)

    results = {}

    # 1. Valores nulos
    null_sum = df.isnull().sum().sum()
    results['null_values'] = null_sum
    print(f"✅ Valores nulos: {null_sum}")

    # 2. Duplicados
    duplicates = df.duplicated().sum()
    results['duplicates'] = duplicates
    print(f"✅ Duplicados completos: {duplicates}")

    # 3. Duplicados en ID
    if 'customerID' in df.columns:
        id_duplicates = df['customerID'].duplicated().sum()
        results['id_duplicates'] = id_duplicates
        print(f"✅ Duplicados en customerID: {id_duplicates}")

    # 4. Tipos de datos incorrectos
    if 'account.Charges.Total' in df.columns:
        if df['account.Charges.Total'].dtype == 'object':
            results['format_errors'] = "Total Charges es object, debería ser numérico"
            print(f"⚠️  account.Charges.Total: tipo incorrecto (object)")

    # 5. Rangos imposibles
    if 'customer.tenure' in df.columns:
        negative_tenure = (df['customer.tenure'] < 0).sum()
        results['negative_tenure'] = negative_tenure
        if negative_tenure > 0:
            print(f"⚠️  tenure negativo: {negative_tenure} registros")

    # 6. Valores categóricos inesperados
    unexpected_counts = {}
    expected_churn = ['Yes', 'No']
    if 'Churn' in df.columns:
        unexpected_churn = set(df['Churn'].unique()) - set(expected_churn)
        if unexpected_churn:
            results['unexpected_churn'] = unexpected_churn
            print(f"⚠️  Valores inesperados en Churn: {unexpected_churn}")

    print("="*60)
    return results

# Ejecutar análisis rápido
quality_report = quick_data_quality_check(df)

🔍 ANÁLISIS RÁPIDO DE CALIDAD DE DATOS
============================================================
✅ Valores nulos: 0
✅ Duplicados completos: 0
✅ Duplicados en customerID: 0
⚠️  account.Charges.Total: tipo incorrecto (object)
⚠️  Valores inesperados en Churn: {''}
============================================================

# 📌 **2. T-ratamiento  de los Datos**: 📌

## 📝 *Se revisan los nombres de cada columna y se eliminan y renombran para poder darles un mejor tratamiento*

In [20]:
# Crear un diccionario de renombrado
rename_dict = {
    'customerID': 'ID_cliente',
    'Churn': 'Deserción',
    'customer.gender': 'Género',
    'customer.SeniorCitizen': 'Jubilado',
    'customer.Partner': 'Socios',
    'customer.Dependents': 'Dependendientes',
    'customer.tenure': 'Antiguedad',
    'phone.PhoneService': 'Servicio_Teléfono',
    'phone.MultipleLines': 'Líneas_Multiples',
    'internet.InternetService': 'Servicio_Internet',
    'internet.OnlineSecurity': 'Seguridad_Online',
    'internet.OnlineBackup': 'Respaldo_online',
    'internet.DeviceProtection': 'Proteccion_dispositivo',
    'internet.TechSupport': 'Soporte_Tecnico',
    'internet.StreamingTV': 'StreamingTV',
    'internet.StreamingMovies': 'StreamingMovies',
    'account.Contract': 'Contrato',
    'account.PaperlessBilling': 'Facturación_sin_papel',
    'account.PaymentMethod': 'Metodo_de_pago',
    'account.Charges.Monthly': 'Cargos_mensuales',
    'account.Charges.Total': 'Cargos_totales'
}
df = df.rename(columns=rename_dict)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_cliente              7267 non-null   object
 1   Deserción               7043 non-null   object
 2   Género                  7267 non-null   object
 3   Jubilado                7267 non-null   int64
 4   Socios                  7267 non-null   object
 5   Dependendientes         7267 non-null   object
 6   Antiguedad              7267 non-null   int64
 7   Servicio_Teléfono       7267 non-null   object
 8   Líneas_Multiples        7267 non-null   object
 9   Servicio_Internet       7267 non-null   object
 10  Seguridad_Online        7267 non-null   object
 11  Respaldo_online         7267 non-null   object
 12  Proteccion_dispositivo  7267 non-null   object
 13  Soporte_Tecnico         7267 non-null   object
 14  StreamingTV             7267 non-null   object
 15  StreamingMovies         7267 non-null   object
 16  Contrato                7267 non-null   object
 17  Facturación_sin_papel   7267 non-null   object
 18  Metodo_de_pago          7267 non-null   object
 19  Cargos_mensuales        7267 non-null   float64
 20  Cargos_totales          7256 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [21]:

df.columns.tolist() # Visualizamos los nombres de los encabezados en lista

['ID_cliente',
 'Deserción',
 'Género',
 'Jubilado',
 'Socios',
 'Dependendientes',
 'Antiguedad',
 'Servicio_Teléfono',
 'Líneas_Multiples',
 'Servicio_Internet',
 'Seguridad_Online',
 'Respaldo_online',
 'Proteccion_dispositivo',
 'Soporte_Tecnico',
 'StreamingTV',
 'StreamingMovies',
 'Contrato',
 'Facturación_sin_papel',
 'Metodo_de_pago',
 'Cargos_mensuales',
 'Cargos_totales']

In [28]:

# Identificamos si hay valores vacios
# Encontrar cadenas vacías ('')
cadenas_vacias = (df == '').sum()
print("Cadenas vacías ('') por columna:")
print(cadenas_vacias[cadenas_vacias > 0])

Cadenas vacías ('') por columna:
Series([], dtype: int64)

In [25]:
# Reemplazar '', ' ', '   ' → np.nan en TODAS las columnas string
df = df.replace(r'^\s*$', np.nan, regex=True)

In [26]:
df['Cargos_totales'] = pd.to_numeric(df['Cargos_totales'], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_cliente              7267 non-null   object
 1   Deserción               7043 non-null   object
 2   Género                  7267 non-null   object
 3   Jubilado                7267 non-null   int64
 4   Socios                  7267 non-null   object
 5   Dependendientes         7267 non-null   object
 6   Antiguedad              7267 non-null   int64
 7   Servicio_Teléfono       7267 non-null   object
 8   Líneas_Multiples        7267 non-null   object
 9   Servicio_Internet       7267 non-null   object
 10  Seguridad_Online        7267 non-null   object
 11  Respaldo_online         7267 non-null   object
 12  Proteccion_dispositivo  7267 non-null   object
 13  Soporte_Tecnico         7267 non-null   object
 14  StreamingTV             7267 non-null   object
 15  StreamingMovies         7267 non-null   object
 16  Contrato                7267 non-null   object
 17  Facturación_sin_papel   7267 non-null   object
 18  Metodo_de_pago          7267 non-null   object
 19  Cargos_mensuales        7267 non-null   float64
 20  Cargos_totales          7256 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [29]:
# Detectar columnas con valores NaN después del reemplazo
columnas_nulas = df.columns[df.isnull().any()].tolist()
print("Columnas con nulls:", columnas_nulas)

Columnas con nulls: ['Deserción', 'Cargos_totales']

In [30]:
for col in columnas_nulas:
    nulos = df[col].isnull().sum()
    porcentaje = df[col].isnull().mean() * 100

    print(f"Columna: {col}")
    print(f" - Cantidad de nulos: {nulos:,}")
    print(f" - Porcentaje: {porcentaje:.4f}%\n")

Columna: Deserción
 - Cantidad de nulos: 224
 - Porcentaje: 3.0824%

Columna: Cargos_totales
 - Cantidad de nulos: 11
 - Porcentaje: 0.1514%

In [32]:

# Eliminar registros vacios o nulls
df = df.dropna(subset=['Cargos_totales', 'Deserción'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_cliente              7032 non-null   object
 1   Deserción               7032 non-null   object
 2   Género                  7032 non-null   object
 3   Jubilado                7032 non-null   int64
 4   Socios                  7032 non-null   object
 5   Dependendientes         7032 non-null   object
 6   Antiguedad              7032 non-null   int64
 7   Servicio_Teléfono       7032 non-null   object
 8   Líneas_Multiples        7032 non-null   object
 9   Servicio_Internet       7032 non-null   object
 10  Seguridad_Online        7032 non-null   object
 11  Respaldo_online         7032 non-null   object
 12  Proteccion_dispositivo  7032 non-null   object
 13  Soporte_Tecnico         7032 non-null   object
 14  StreamingTV             7032 non-null   object
 15  StreamingMovies         7032 non-null   object
 16  Contrato                7032 non-null   object
 17  Facturación_sin_papel   7032 non-null   object
 18  Metodo_de_pago          7032 non-null   object
 19  Cargos_mensuales        7032 non-null   float64
 20  Cargos_totales          7032 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [33]:
df.nunique()

ID_cliente                7032
Deserción                    2
Género                       2
Jubilado                     2
Socios                       2
Dependendientes              2
Antiguedad                  72
Servicio_Teléfono            2
Líneas_Multiples             3
Servicio_Internet            3
Seguridad_Online             3
Respaldo_online              3
Proteccion_dispositivo       3
Soporte_Tecnico              3
StreamingTV                  3
StreamingMovies              3
Contrato                     3
Facturación_sin_papel        2
Metodo_de_pago               4
Cargos_mensuales          1584
Cargos_totales            6530
dtype: int64

In [34]:
columnas_object = df.select_dtypes(include='object').columns.tolist()
print(columnas_object)

['ID_cliente', 'Deserción', 'Género', 'Socios', 'Dependendientes', 'Servicio_Teléfono', 'Líneas_Multiples', 'Servicio_Internet', 'Seguridad_Online', 'Respaldo_online', 'Proteccion_dispositivo', 'Soporte_Tecnico', 'StreamingTV', 'StreamingMovies', 'Contrato', 'Facturación_sin_papel', 'Metodo_de_pago']

In [35]:
columnas_object = df.select_dtypes(include='object').columns

for col in columnas_object:
    print(f"\n Columna: {col}")
    print(df[col].value_counts())

 Columna: ID_cliente
ID_cliente
9995-HOTOH    1
0002-ORFBO    1
0003-MKNFE    1
0004-TLHLJ    1
0011-IGKFF    1
             ..
0018-NYROU    1
0017-IUDMW    1
0017-DINOC    1
0016-QLJIS    1
0015-UOCOJ    1
Name: count, Length: 7032, dtype: int64

 Columna: Deserción
Deserción
No     5163
Yes    1869
Name: count, dtype: int64

 Columna: Género
Género
Male      3549
Female    3483
Name: count, dtype: int64

 Columna: Socios
Socios
No     3639
Yes    3393
Name: count, dtype: int64

 Columna: Dependendientes
Dependendientes
No     4933
Yes    2099
Name: count, dtype: int64

 Columna: Servicio_Teléfono
Servicio_Teléfono
Yes    6352
No      680
Name: count, dtype: int64

 Columna: Líneas_Multiples
Líneas_Multiples
No                  3385
Yes                 2967
No phone service     680
Name: count, dtype: int64

 Columna: Servicio_Internet
Servicio_Internet
Fiber optic    3096
DSL            2416
No             1520
Name: count, dtype: int64

 Columna: Seguridad_Online
Seguridad_Online
No                     3497
Yes                    2015
No internet service    1520
Name: count, dtype: int64

 Columna: Respaldo_online
Respaldo_online
No                     3087
Yes                    2425
No internet service    1520
Name: count, dtype: int64

 Columna: Proteccion_dispositivo
Proteccion_dispositivo
No                     3094
Yes                    2418
No internet service    1520
Name: count, dtype: int64

 Columna: Soporte_Tecnico
Soporte_Tecnico
No                     3472
Yes                    2040
No internet service    1520
Name: count, dtype: int64

 Columna: StreamingTV
StreamingTV
No                     2809
Yes                    2703
No internet service    1520
Name: count, dtype: int64

 Columna: StreamingMovies
StreamingMovies
No                     2781
Yes                    2731
No internet service    1520
Name: count, dtype: int64

 Columna: Contrato
Contrato
Month-to-month    3875
Two year          1685
One year          1472
Name: count, dtype: int64

 Columna: Facturación_sin_papel
Facturación_sin_papel
Yes    4168
No     2864
Name: count, dtype: int64

 Columna: Metodo_de_pago
Metodo_de_pago
Electronic check             2365
Mailed check                 1604
Bank transfer (automatic)    1542
Credit card (automatic)      1521
Name: count, dtype: int64

In [37]:
## Se crea una columna CUENTAS DIARIAS, para analizar el valor diario y ver el comportamiento de los clientes a lo largo del tiempo.

# Si creaste df como un slice de otro DataFrame
df = df.copy()  # Esto crea una copia explícita

# Ahora puedes modificar sin advertencias
df['Cuentas_Diarias'] = round(df['Cargos_mensuales'] / 30, 2)

In [38]:
df.head()

,ID_cliente,Deserción,Género,Jubilado,Socios,Dependendientes,Antiguedad,Servicio_Teléfono,Líneas_Multiples,Servicio_Internet,...,Proteccion_dispositivo,Soporte_Tecnico,StreamingTV,StreamingMovies,Contrato,Facturación_sin_papel,Metodo_de_pago,Cargos_mensuales,Cargos_totales,Cuentas_Diarias
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30,2.19
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40,2.00
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.46
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.27
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40,2.80